name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install
      - name: Build Next.js app
        run: npm run build
      - name: Deploy to Netlify
        uses: netlify/actions@v2
        with:
          publish-dir: ./school-hub/.next
          # Replace with your Netlify site ID
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # Replace with your Netlify auth token
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
